// apps/project-2/src/app/page.tsx
"use client";

import { Activity, Heart, Moon, Sun, Settings, Bell, Flame } from 'lucide-react';
import { motion } from 'framer-motion';

export default function Home() {
  return (
    <div className="min-h-screen bg-[#050505] text-slate-200 font-sans selection:bg-emerald-500/30">
      {/* Top App Bar */}
      <motion.header 
        initial={{ y: -100 }}
        animate={{ y: 0 }}
        className="h-20 border-b border-white/5 flex items-center justify-between px-8 bg-black/50 backdrop-blur-xl sticky top-0 z-50"
      >
        <div className="flex items-center gap-4">
          <div className="w-10 h-10 rounded-full bg-emerald-500/20 flex items-center justify-center border border-emerald-500/50">
            <Heart className="text-emerald-400 w-5 h-5" />
          </div>
          <h1 className="font-bold text-xl tracking-tight">Aura <span className="text-emerald-400 font-light">Health AI</span></h1>
        </div>
        <div className="flex items-center gap-4">
          <button className="p-2 hover:bg-white/10 rounded-full transition"><Bell className="w-5 h-5" /></button>
          <button className="p-2 hover:bg-white/10 rounded-full transition"><Settings className="w-5 h-5" /></button>
          <div className="w-10 h-10 rounded-full bg-gradient-to-tr from-emerald-500 to-blue-500 p-[2px]">
            <div className="w-full h-full bg-black rounded-full border border-black overflow-hidden">
              <img src="https://ui-avatars.com/api/?name=User&background=0D8ABC&color=fff" alt="User" />
            </div>
          </div>
        </div>
      </motion.header>

      <main className="max-w-6xl mx-auto p-8 flex gap-8">
        {/* Left Column: Vitals */}
        <div className="w-80 flex flex-col gap-6">
          <motion.div 
            initial={{ opacity: 0, x: -50 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.1 }}
            className="bg-white/5 border border-white/10 rounded-3xl p-6 relative overflow-hidden group hover:border-emerald-500/30 transition-colors"
          >
            <div className="absolute top-0 right-0 w-32 h-32 bg-emerald-500/10 rounded-full blur-2xl group-hover:bg-emerald-500/20 transition-all"></div>
            <div className="flex justify-between items-start mb-8 relative z-10">
              <div>
                <h3 className="text-slate-400 text-sm font-medium">Readiness Score</h3>
                <div className="text-5xl font-bold text-white mt-1">94<span className="text-xl text-emerald-400 ml-1">Optimal</span></div>
              </div>
              <Activity className="w-6 h-6 text-emerald-400" />
            </div>
            <div className="space-y-3 relative z-10">
              <div className="flex justify-between text-sm">
                <span className="text-slate-400">Resting HR</span>
                <span className="font-mono text-white">48 bpm</span>
              </div>
              <div className="flex justify-between text-sm">
                <span className="text-slate-400">HRV</span>
                <span className="font-mono text-white">82 ms</span>
              </div>
            </div>
          </motion.div>

          <motion.div 
            initial={{ opacity: 0, x: -50 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.2 }}
            className="bg-white/5 border border-white/10 rounded-3xl p-6 relative overflow-hidden group hover:border-orange-500/30 transition-colors"
          >
            <div className="absolute top-0 right-0 w-32 h-32 bg-orange-500/10 rounded-full blur-2xl group-hover:bg-orange-500/20 transition-all"></div>
            <div className="flex justify-between items-start mb-8 relative z-10">
              <div>
                <h3 className="text-slate-400 text-sm font-medium">Activity Goal</h3>
                <div className="text-4xl font-bold text-white mt-1">2,450<span className="text-lg text-slate-500 ml-1">/ 3000 kcal</span></div>
              </div>
              <Flame className="w-6 h-6 text-orange-400" />
            </div>
            <div className="w-full h-3 bg-white/10 rounded-full overflow-hidden">
              <div className="h-full bg-gradient-to-r from-orange-500 to-amber-400 w-[81%]"></div>
            </div>
          </motion.div>
        </div>

        {/* Center/Right: Sleep AI & Trends */}
        <div className="flex-1 flex flex-col gap-6">
          <motion.div 
            initial={{ opacity: 0, y: 50 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.3 }}
            className="bg-gradient-to-br from-blue-900/40 to-purple-900/40 border border-blue-500/20 rounded-3xl p-8 relative overflow-hidden"
          >
            <div className="flex justify-between items-start relative z-10">
              <div className="max-w-md">
                <div className="flex items-center gap-2 mb-4">
                  <Moon className="w-5 h-5 text-blue-400" />
                  <span className="text-blue-400 font-semibold tracking-wider text-sm">AI SLEEP ANALYSIS</span>
                </div>
                <h2 className="text-3xl font-bold text-white mb-4">Your deep sleep increased by 14% last night.</h2>
                <p className="text-slate-300 leading-relaxed">
                  Our on-device CoreML model detected optimal body temperature regulation between 2AM and 4AM. This correlates with the new magnesium supplement protocol you started 3 days ago.
                </p>
              </div>
              <div className="text-right">
                <div className="text-6xl font-bold text-white">8<span className="text-2xl text-blue-400">h</span> 12<span className="text-2xl text-blue-400">m</span></div>
                <div className="text-slate-400 mt-2 font-medium">Total Sleep Time</div>
              </div>
            </div>
            
            {/* Sleep Graph Simulation */}
            <div className="mt-12 h-32 flex items-end gap-1 relative z-10">
              {[40, 20, 60, 80, 20, 10, 40, 60, 90, 30, 20, 50, 70, 80, 40, 10].map((val, i) => (
                <motion.div 
                  key={i} 
                  initial={{ height: 0 }}
                  animate={{ height: `${val}%` }}
                  transition={{ delay: 0.5 + (i * 0.05), duration: 0.5 }}
                  className="flex-1 rounded-t-sm transition-colors hover:opacity-80 cursor-pointer" 
                  style={{ 
                    backgroundColor: val > 70 ? '#3b82f6' : val > 40 ? '#8b5cf6' : '#64748b' 
                  }}>
                </motion.div>
              ))}
            </div>
          </motion.div>

          <div className="grid grid-cols-2 gap-6 flex-1">
            <div className="bg-white/5 border border-white/10 rounded-3xl p-6">
               <h3 className="text-slate-400 text-sm font-medium mb-6">Hydration Tracker</h3>
               <div className="flex items-center justify-center h-48 relative">
                 {/* Circular Progress Simulation */}
                 <div className="w-40 h-40 rounded-full border-[12px] border-white/5 relative flex items-center justify-center">
                   <div className="absolute inset-[-12px] rounded-full border-[12px] border-cyan-500 border-l-transparent border-b-transparent transform rotate-45"></div>
                   <div className="text-center">
                     <div className="text-3xl font-bold text-white">64<span className="text-sm text-cyan-400 ml-1">oz</span></div>
                     <div className="text-xs text-slate-500 mt-1">Goal: 100oz</div>
                   </div>
                 </div>
               </div>
            </div>
            
            <div className="bg-white/5 border border-white/10 rounded-3xl p-6 flex flex-col justify-center items-center text-center">
               <div className="w-16 h-16 bg-emerald-500/20 rounded-2xl flex items-center justify-center mb-4">
                 <Activity className="w-8 h-8 text-emerald-400" />
               </div>
               <h3 className="text-white font-bold text-lg mb-2">Connect Apple Health</h3>
               <p className="text-slate-400 text-sm mb-6">Sync your clinical records for deeper ML predictions.</p>
               <button className="px-6 py-2 bg-white text-black font-semibold rounded-full hover:bg-slate-200 transition">
                 Sync Now
               </button>
            </div>
          </div>

        </div>
      </main>
    </div>
  );
}

// apps/project-5/app/app.vue
<script setup>
import { ref } from 'vue'
import { 
  ShoppingBag, Search, Menu, 
  ChevronRight, Play, ArrowUpRight, X, Trash2
} from 'lucide-vue-next'

const isCartOpen = ref(false)
const cartItems = ref([
  { id: 1, name: 'Obsidian Chronograph', price: 12450, qty: 1, image: 'https://images.unsplash.com/photo-1584916201218-f4242ceb4809?q=80&w=2015&auto=format&fit=crop' },
  { id: 2, name: 'Noir Eau de Parfum', price: 450, qty: 2, image: 'https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?q=80&w=1974&auto=format&fit=crop' }
])

const cartTotal = computed(() => {
  return cartItems.value.reduce((total, item) => total + (item.price * item.qty), 0)
})

const removeItem = (id) => {
  cartItems.value = cartItems.value.filter(item => item.id !== id)
}
</script>

<template>
  <div class="min-h-screen bg-[#0a0a0a] text-white selection:bg-amber-500/30">
    <!-- Navbar -->
    <nav class="absolute top-0 w-full z-50 px-8 py-6 flex items-center justify-between">
      <div class="flex items-center gap-12">
        <h1 class="text-2xl font-bold tracking-widest uppercase">AURA<span class="font-light">MAISON</span></h1>
        <div class="hidden md:flex gap-8 text-sm uppercase tracking-widest font-semibold text-slate-300">
          <a href="#" class="hover:text-white transition">Collection</a>
          <a href="#" class="hover:text-white transition">Atelier</a>
          <a href="#" class="hover:text-white transition">Bespoke</a>
        </div>
      </div>
      <div class="flex items-center gap-6">
        <Search class="w-5 h-5 cursor-pointer hover:text-amber-400 transition" />
        <div class="relative cursor-pointer group" @click="isCartOpen = true">
          <ShoppingBag class="w-5 h-5 group-hover:text-amber-400 transition" />
          <span v-if="cartItems.length > 0" class="absolute -top-2 -right-2 bg-amber-500 text-black text-[10px] font-bold w-4 h-4 rounded-full flex items-center justify-center">{{ cartItems.length }}</span>
        </div>
        <Menu class="w-6 h-6 md:hidden cursor-pointer" />
      </div>
    </nav>

    <!-- Hero Section -->
    <section class="h-screen relative flex items-center justify-center overflow-hidden">
      <!-- Simulated 3D Background/Video -->
      <div class="absolute inset-0 bg-black">
        <div class="absolute inset-0 bg-gradient-to-b from-black/60 via-transparent to-[#0a0a0a] z-10"></div>
        <img 
          src="https://images.unsplash.com/photo-1549439602-43ebca2327af?q=80&w=2070&auto=format&fit=crop" 
          alt="Luxury Fashion" 
          class="w-full h-full object-cover opacity-60 scale-105 transform origin-center animate-[slowPan_30s_infinite_alternate]"
        />
      </div>

      <div class="relative z-20 text-center px-4 max-w-4xl mx-auto">
        <p class="uppercase tracking-[0.3em] text-amber-400 text-sm mb-6 font-semibold">The Obsidian Collection</p>
        <h2 class="text-6xl md:text-8xl font-light tracking-tighter mb-8 leading-none">
          Redefining <br/> <span class="font-bold italic">Elegance.</span>
        </h2>
        <div class="flex items-center justify-center gap-6">
          <button class="px-8 py-4 bg-white text-black font-semibold uppercase tracking-wider text-sm hover:bg-amber-400 transition-colors">
            Explore Collection
          </button>
          <button class="w-12 h-12 rounded-full border border-white/30 flex items-center justify-center hover:bg-white/10 transition-colors">
            <Play class="w-4 h-4 ml-1" />
          </button>
        </div>
      </div>
    </section>

    <!-- Featured Products (Bento Grid) -->
    <section class="py-32 px-4 md:px-8 max-w-[1600px] mx-auto">
      <div class="flex justify-between items-end mb-16">
        <h3 class="text-4xl font-light tracking-tight">Curated <span class="font-bold">Masterpieces</span></h3>
        <a href="#" class="hidden md:flex items-center gap-2 uppercase tracking-widest text-xs font-semibold text-amber-400 hover:text-amber-300">
          View All <ArrowUpRight class="w-4 h-4" />
        </a>
      </div>

      <div class="grid grid-cols-1 md:grid-cols-4 grid-rows-[400px_400px] gap-4">
        <!-- Item 1 (Large) -->
        <div class="md:col-span-2 md:row-span-2 relative group overflow-hidden bg-white/5 cursor-pointer" @click="isCartOpen = true">
          <img src="https://images.unsplash.com/photo-1584916201218-f4242ceb4809?q=80&w=2015&auto=format&fit=crop" class="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105 opacity-80 group-hover:opacity-100" />
          <div class="absolute inset-0 bg-gradient-to-t from-black/90 via-black/20 to-transparent"></div>
          <div class="absolute bottom-8 left-8 right-8 flex justify-between items-end">
            <div>
              <p class="text-amber-400 text-xs uppercase tracking-widest mb-2 font-bold">Limited Edition</p>
              <h4 class="text-3xl font-light">Obsidian Chronograph</h4>
            </div>
            <p class="text-xl font-mono">$12,450</p>
          </div>
          <div class="absolute top-8 right-8 translate-x-12 opacity-0 group-hover:translate-x-0 group-hover:opacity-100 transition-all duration-500 bg-white/10 backdrop-blur-md p-3 rounded-full hover:bg-amber-400 hover:text-black">
            <ShoppingBag class="w-5 h-5" />
          </div>
        </div>

        <!-- Item 2 -->
        <div class="md:col-span-2 relative group overflow-hidden bg-white/5 cursor-pointer">
          <img src="https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=2069&auto=format&fit=crop" class="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105 opacity-80 group-hover:opacity-100" />
          <div class="absolute inset-0 bg-gradient-to-t from-black/90 via-black/20 to-transparent"></div>
          <div class="absolute bottom-6 left-6 right-6 flex justify-between items-end">
            <div>
              <h4 class="text-xl font-light">Leather Weekender</h4>
            </div>
            <p class="text-lg font-mono">$3,200</p>
          </div>
        </div>

        <!-- Item 3 -->
        <div class="relative group overflow-hidden bg-white/5 cursor-pointer">
          <img src="https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?q=80&w=1974&auto=format&fit=crop" class="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105 opacity-80 group-hover:opacity-100" />
          <div class="absolute inset-0 bg-gradient-to-t from-black/90 via-black/20 to-transparent"></div>
          <div class="absolute bottom-6 left-6 right-6 flex justify-between items-end">
            <div>
              <h4 class="text-lg font-light">Noir Eau de Parfum</h4>
            </div>
            <p class="text-base font-mono">$450</p>
          </div>
        </div>

        <!-- Item 4 -->
        <div class="relative group overflow-hidden bg-white/5 cursor-pointer">
          <div class="absolute inset-0 bg-amber-900/20 flex flex-col items-center justify-center p-8 text-center transition-colors group-hover:bg-amber-900/40">
            <h4 class="text-2xl font-light mb-4">Book a Private Fitting</h4>
            <div class="w-12 h-12 rounded-full border border-amber-400 flex items-center justify-center text-amber-400 group-hover:bg-amber-400 group-hover:text-black transition-colors">
              <ChevronRight class="w-5 h-5" />
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- Cart Drawer (Micro-interaction) -->
    <Transition name="slide">
      <div v-if="isCartOpen" class="fixed inset-0 z-[100] flex justify-end">
        <div class="absolute inset-0 bg-black/60 backdrop-blur-sm cursor-pointer" @click="isCartOpen = false"></div>
        <div class="w-full md:w-[450px] bg-[#0a0a0a] h-full relative z-10 border-l border-white/10 flex flex-col shadow-2xl">
          <div class="p-6 border-b border-white/10 flex justify-between items-center">
            <h3 class="text-xl font-light tracking-widest uppercase">Your Atelier <span class="font-bold">Cart</span></h3>
            <button @click="isCartOpen = false" class="p-2 hover:bg-white/10 rounded-full transition-colors">
              <X class="w-5 h-5" />
            </button>
          </div>
          
          <div class="flex-1 overflow-y-auto p-6 space-y-6">
            <div v-if="cartItems.length === 0" class="h-full flex flex-col items-center justify-center text-slate-500">
              <ShoppingBag class="w-12 h-12 mb-4 opacity-50" />
              <p class="uppercase tracking-widest text-sm">Your cart is empty</p>
            </div>
            
            <div v-for="item in cartItems" :key="item.id" class="flex gap-4 group">
              <div class="w-24 h-24 bg-white/5 rounded-lg overflow-hidden flex-shrink-0">
                <img :src="item.image" class="w-full h-full object-cover" />
              </div>
              <div class="flex-1 flex flex-col justify-center">
                <h4 class="font-medium text-sm mb-1">{{ item.name }}</h4>
                <p class="text-slate-400 text-xs mb-3">Qty: {{ item.qty }}</p>
                <p class="font-mono text-sm">${{ item.price.toLocaleString() }}</p>
              </div>
              <div class="flex items-center">
                <button @click="removeItem(item.id)" class="p-2 text-slate-500 hover:text-red-400 opacity-0 group-hover:opacity-100 transition-all">
                  <Trash2 class="w-4 h-4" />
                </button>
              </div>
            </div>
          </div>

          <div class="p-6 border-t border-white/10 bg-black">
            <div class="flex justify-between items-center mb-6">
              <span class="text-sm text-slate-400 uppercase tracking-widest">Subtotal</span>
              <span class="text-xl font-mono">${{ cartTotal.toLocaleString() }}</span>
            </div>
            <button class="w-full py-4 bg-white text-black font-bold uppercase tracking-widest text-sm hover:bg-amber-400 transition-colors">
              Proceed to Checkout
            </button>
          </div>
        </div>
      </div>
    </Transition>
  </div>
</template>

<style>
@keyframes slowPan {
  from { transform: scale(1.05) translate(0, 0); }
  to { transform: scale(1.1) translate(-2%, 2%); }
}

/* Vue Transition for Cart Drawer */
.slide-enter-active,
.slide-leave-active {
  transition: all 0.4s cubic-bezier(0.16, 1, 0.3, 1);
}
.slide-enter-from .bg-black\/60,
.slide-leave-to .bg-black\/60 {
  opacity: 0;
}
.slide-enter-from .w-full,
.slide-leave-to .w-full {
  transform: translateX(100%);
}
</style>
